version: "3"

services:
  db:
    image: influxdb:1.8
    ports: 
      - '8086:8086'
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/influxdb
    restart: always

  weather:
    image: weather
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - api.env

volumes:
  db_data: {}
  
