{
 "title": "VEHICLES",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Realtime Bus Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Route $tag_route",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay",
     "query": "SELECT \"data\" FROM \"delay\" WHERE $timeFilter AND \"route\" =~ /^(23|66|111|57|1)$/ GROUP BY \"route\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Average Delay in Seconds per Stop",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Stop $tag_stop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"data\") FROM \"delay\" WHERE  $timeFilter AND \"route\" =~ /^(23|66|111|57|1)$/ GROUP BY  \"stop\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Realtime Average Delay in Seconds per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "avg delay (s)",
     "query": "SELECT mean(\"data\") AS \"avg_delay_per_hour\" FROM \"delay\" WHERE $timeFilter GROUP BY time(1h)"
    }
   ]
  },
  {
   "title": "Average Delay in Seconds Per Route",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Route $tag_route",
     "query": "SELECT mean(\"data\") FROM \"delay\" WHERE  $timeFilter AND \"route\" =~ /^(23|66|111|57|1)$/ GROUP BY  \"route\""
    }
   ]
  }
 ]
}